version: "3"

services:
  nginx:
    image: nginx:1.27.0-alpine
    restart: always
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    logging:
      driver: local
    networks:
      - edumgmt-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  #certbot:
  #  image: certbot/certbot:v2.11.0
  #  restart: always
  #  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #  volumes:
  #    - ./certbot/conf:/etc/letsencrypt
  #    - ./certbot/www:/var/www/certbot
  #  depends_on:
  #    - nginx

networks:
  edumgmt-server:
    external:
      name: edumgmt-server_default
